name: Deploy AI2Fin Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Mintlify CLI
      run: npm install -g @mintlify/cli
      
    - name: Validate documentation
      run: mintlify validate
      
    - name: Build documentation
      run: mintlify build
      
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ai2fin-docs
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Cloudflare Workers (Subdirectory routing)
      if: github.ref == 'refs/heads/main'
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/workers/scripts/ai2fin-router" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/javascript" \
          --data-binary @worker-script.js
          
    - name: Notify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Documentation deployed successfully to https://ai2fin.com/docs"
        
  preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Mintlify CLI
      run: npm install -g @mintlify/cli
      
    - name: Build preview
      run: mintlify build
      
    - name: Deploy preview to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ai2fin-docs-preview
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        preview: true
